--- # this is my first playbook
- hosts: all
  user: ansadmin
  become: true
  connection: ssh
  gather_facts: no
  tasks:
   - name: Execute below command
     command: /bin/false
     ignore_errors: yes
   - name: Install httpd software on host systems
     yum: pkg=httpd state=installed

